/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Kouhei Ito
 * Part of StampFly Ecosystem (SILS host bench — ESP-IDF host platform).
 */

/**
 * @file sdkconfig.h
 * @brief Host shim for the ESP-IDF project configuration header.
 *        ESP-IDF プロジェクト設定ヘッダのホスト用シム。
 *
 * On a real build sdkconfig.h is generated by Kconfig from menuconfig. Here we
 * provide ONLY the CONFIG_* macros the StampFly firmware actually references in
 * its C/C++ source (not the thousands of options the full generator emits), so
 * the firmware compiles unmodified on the host.
 *
 * 実ビルドでは sdkconfig.h は menuconfig から Kconfig が生成する。ここでは
 * StampFly ファームが C/C++ ソースで実際に参照する CONFIG_* マクロ "だけ" を
 * 提供し（フル生成器が吐く数千のオプションではなく）、ファームを無改変で
 * ホストコンパイルできるようにする。
 */

#pragma once

// -----------------------------------------------------------------------------
// Target / RTOS identity
// ターゲット / RTOS 識別
//
// StampFly is an ESP32-S3 board. The led_strip managed component branches on
// CONFIG_IDF_TARGET_ESP32 / _ESP32S2 with #if, so those MUST be defined to 0
// (preprocessor treats an undefined identifier in #if as 0, but defining them
// explicitly is clearer and avoids -Wundef warnings).
// StampFly は ESP32-S3 基板。led_strip コンポーネントは
// CONFIG_IDF_TARGET_ESP32 / _ESP32S2 を #if で分岐するため、これらは 0 に
// 定義する必要がある（未定義識別子は #if 内で 0 扱いだが、明示すると
// -Wundef 警告も避けられ明快）。
#define CONFIG_IDF_TARGET_ESP32S3   1
#define CONFIG_IDF_TARGET_ESP32     0
#define CONFIG_IDF_TARGET_ESP32S2   0

// FreeRTOS tick rate. SILS convention: 1 tick = 1 ms (1000 Hz), matching the
// firmware's configTICK_RATE_HZ.
// FreeRTOS の tick レート。SILS の取り決めは 1 tick = 1 ms（1000 Hz）で、
// ファームの configTICK_RATE_HZ と一致。
#define CONFIG_FREERTOS_HZ          1000

// -----------------------------------------------------------------------------
// led_strip (espressif__led_strip) RMT options
// led_strip コンポーネントの RMT オプション
//
// RMT_ISR_IRAM_SAFE gates whether the encoder is placed in IRAM. Irrelevant on
// the host; leave at 0 so the non-IRAM code path is taken.
// RMT_ISR_IRAM_SAFE はエンコーダを IRAM に置くかを決める。ホストでは無関係
// なので 0 にして非 IRAM のコードパスを通す。
#define CONFIG_RMT_ISR_IRAM_SAFE    0

// -----------------------------------------------------------------------------
// Console
// コンソール
//
// StampFly uses the USB-CDC console on ESP32-S3. Referenced only in a comment
// today, but defined here to keep the surface complete for any #ifdef use.
// StampFly は ESP32-S3 の USB-CDC コンソールを使う。現状はコメントでのみ参照
// されるが、将来の #ifdef 利用に備えて定義しておく。
#define CONFIG_ESP_CONSOLE_USB_CDC  1

// -----------------------------------------------------------------------------
// VL53L3CX (sf_hal_vl53l3cx) ToF pin / timing configuration
// VL53L3CX ToF のピン / タイミング設定
//
// stampfly_tof_config.h #defines its public macros directly from these. Values
// mirror the component's Kconfig defaults so the host build matches hardware.
// stampfly_tof_config.h はこれらから公開マクロを直接 #define する。値は
// コンポーネントの Kconfig デフォルトに合わせ、ホストビルドを実機に一致させる。
#define CONFIG_STAMPFLY_TOF_I2C_SDA_GPIO        3
#define CONFIG_STAMPFLY_TOF_I2C_SCL_GPIO        4
#define CONFIG_STAMPFLY_TOF_I2C_FREQ_HZ         400000
#define CONFIG_STAMPFLY_TOF_FRONT_XSHUT_GPIO    9
#define CONFIG_STAMPFLY_TOF_FRONT_INT_GPIO      8
#define CONFIG_STAMPFLY_TOF_BOTTOM_XSHUT_GPIO   7
#define CONFIG_STAMPFLY_TOF_BOTTOM_INT_GPIO     6
#define CONFIG_STAMPFLY_TOF_TIMING_BUDGET_MS    33
