/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Kouhei Ito
 *
 * Part of StampFly Ecosystem (vehicle_new firmware).
 * https://github.com/M5Fly-kanazawa/stampfly_ecosystem
 */

/**
 * @file params.hpp
 * @brief Parameter system — single-macro definition with NVS persistence
 *        パラメータシステム — 1行マクロ定義 + NVS永続化
 *
 * Adding a parameter requires only one line in params.def.
 * Each parameter gets: variable, name, default, min, max, callback.
 * Access via WiFi and CLI. Persistence via NVS.
 *
 * パラメータ追加はparams.defに1行追加するだけ。
 * 各パラメータは変数、名前、デフォルト、最小、最大、コールバックを持つ。
 * WiFiおよびCLI経由でアクセス可能。NVS経由で永続化。
 *
 * @design requirements.md §3 — Parameter management                   [--]
 * @design detailed_design.md §6 — Single-macro parameter definition   [--]
 * @design coding_and_education.md §2 — Bilingual comments             [--]
 */

#pragma once

#include <cstdint>
#include <cstddef>

namespace sf {
namespace params {

// =============================================================================
// Parameter Types
// パラメータ型
// =============================================================================

enum class ParamType : uint8_t {
    FLOAT = 0,
    BOOL  = 1,
    INT   = 2,
};

/// Callback function type — called when parameter value changes
/// コールバック関数型 — パラメータ値の変更時に呼ばれる
using ParamCallback = void (*)(void);

// =============================================================================
// Parameter Entry (internal table structure)
// パラメータエントリ（内部テーブル構造体）
// =============================================================================

struct ParamEntry {
    const char* name;         // Parameter name / パラメータ名
    ParamType type;           // Value type / 値の型
    void* value_ptr;          // Pointer to variable / 変数へのポインタ
    float default_val;        // Default value / デフォルト値
    float min_val;            // Minimum value / 最小値
    float max_val;            // Maximum value / 最大値
    ParamCallback callback;   // Change callback (null = none) / 変更コールバック
};

// =============================================================================
// Parameter Variables — generated by macros in params.def
// パラメータ変数 — params.defのマクロで生成
// =============================================================================

// X-macro pattern: params.def is included multiple times with different
// macro definitions to generate variables, table entries, etc.
//
// Xマクロパターン: params.defは異なるマクロ定義で複数回includeされ、
// 変数、テーブルエントリ等を生成する。

// Declare parameter variables
// パラメータ変数を宣言
#define PARAM_FLOAT(name, default_val, min_val, max_val, callback) \
    extern float param_##__LINE__;
#define PARAM_BOOL(name, default_val, min_val, max_val, callback) \
    extern bool param_bool_##__LINE__;
#define PARAM_INT(name, default_val, min_val, max_val, callback) \
    extern int32_t param_int_##__LINE__;

// Note: actual variable names are generated uniquely in params.cpp
// 注: 実際の変数名はparams.cppで一意に生成される

#undef PARAM_FLOAT
#undef PARAM_BOOL
#undef PARAM_INT

// =============================================================================
// Public API
// 公開API
//
// @design detailed_design.md §6 — Parameter access API                [--]
// =============================================================================

/// Initialize parameter system — load from NVS or use defaults
/// パラメータシステムを初期化する — NVSから読み込みまたはデフォルトを使用
void init();

/// Get parameter value by name
/// 名前でパラメータ値を取得する
///
/// @return true if parameter found / パラメータが見つかればtrue
bool get_float(const char* name, float& out);
bool get_bool(const char* name, bool& out);
bool get_int(const char* name, int32_t& out);

/// Set parameter value by name
/// 名前でパラメータ値を設定する
///
/// Validates range, updates value, calls callback, saves to NVS.
/// 範囲を検証し、値を更新し、コールバックを呼び、NVSに保存する。
///
/// @return true if set succeeded / 設定成功ならtrue
bool set_float(const char* name, float value);
bool set_bool(const char* name, bool value);
bool set_int(const char* name, int32_t value);

/// Save all parameters to NVS
/// 全パラメータをNVSに保存する
void save();

/// Load all parameters from NVS
/// 全パラメータをNVSから読み込む
void load();

/// Reset all parameters to default values
/// 全パラメータをデフォルト値にリセットする
void reset_all();

/// Print all parameters (for CLI)
/// 全パラメータを表示する（CLI用）
void list();

/// Get number of registered parameters
/// 登録済みパラメータ数を取得する
int count();

/// Get parameter entry by index (for iteration)
/// インデックスでパラメータエントリを取得する（反復用）
const ParamEntry* entry(int index);

}  // namespace params
}  // namespace sf
